# Generated by Django 3.2.15 on 2022-09-25 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('key_qr', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('key_notes', models.TextField(blank=True, null=True)),
                ('qr_image', models.ImageField(upload_to='qrcode/keys')),
                ('status', models.CharField(default='Available', max_length=50)),
            ],
            options={
                'verbose_name': 'Keys',
                'verbose_name_plural': 'Keys',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_qr', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('qr_image', models.ImageField(upload_to='qrcode/person')),
            ],
            options={
                'verbose_name': 'Persons',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='AssignedKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KeyLogger.keys')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KeyLogger.person')),
            ],
            options={
                'verbose_name': 'Assigned Keys',
                'verbose_name_plural': 'Assigned Keys',
            },
        ),
    ]
